modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/TheKiritoPlayer20/MoreOresInONE/issues"
#displayURL="http://example.com/"
logoFile="moione_logo.png"

[[mods]]
modId="moreoresinone"
version="${file.jarVersion}"
displayName="More Ores in ONE"
#updateJSONURL="http://myurl.me/"


credits="Textures by: TheLuigiplayer, Code by: KiritoGames20"
authors="KiritoGames20 & TheLuigiplayer"
description='''
The More Ores in ONE Mod. It adds Ores in the Overworld, in the Nether and the End.
Disclaimer: Make sure to download this mod from Curseforge or PlanetMinecraft.
'''


[[dependencies.moreoresinone]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[28.0.45,)" #mandatory
    ordering="NONE"
    side="BOTH"


[[dependencies.moreoresinone]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"