
#Config File of the More Ores In ONE mod.
[Armor]

	[Armor."Status Effect"]
		#Enable if full Armor sets should give Potion Effects or not(Default: true).
		enable_statuseffects = true

["Ore Generation"]

	["Ore Generation".Experience]
		#Enable that fortune boosts the experience that you can get from mining(Default: true).
		enable_fortune = true

		["Ore Generation".Experience.Points]

			["Ore Generation".Experience.Points.Nether]
				#Set the Max Experience you can get out of the Experience Nether Ore (Default: 30).
				#Range: 0 ~ 999999999
				max_exp_nether = 30
				#Set the Min Experience you can get out of the Experience Nether Ore (Default: 20).
				#Range: 0 ~ 999999999
				min_exp_nether = 20

			["Ore Generation".Experience.Points.Overworld]
				#Set the Min Experience you can get out of the Experience Overworld Ore (Default: 10).
				#Range: 0 ~ 999999999
				min_exp_overworld = 10
				#Set the Max Experience you can get out of the Experience Overworld Ore (Default: 20).
				#Range: 0 ~ 999999999
				max_exp_overworld = 20

			["Ore Generation".Experience.Points.End]
				#Set the Min Experience you can get out of the Experience End Ore (Default: 30).
				#Range: 0 ~ 999999999
				min_exp_end = 30
				#Set the Max Experience you can get out of the Experience End Ore (Default: 40).
				#Range: 0 ~ 999999999
				max_exp_end = 40

		["Ore Generation".Experience.Nether]
			#Set the Count of the Experience Ore how much can spawn per Chunk in the Nether(Default: 5).
			#Range: 1 ~ 255
			count_nether_experience = 5
			#Enable the Generation of the Nether Experience Ore (Default: true).
			generate_nether_experience = true
			#Set the Max Height of the Experience Ore in the Nether (Default: 128).
			#Range: 0 ~ 128
			max_height_nether_experience = 128
			#Set the Min Height of the Experience Ore in the Nether (Default: 0).
			#Range: 0 ~ 128
			min_height_nether_experience = 0

		["Ore Generation".Experience.Overworld]
			#Enable the Generation of the Overworld Experience Ore(Default: true).
			generate_overworld_experience = true
			#Set the Count of the Experience Ore how much can spawn per Chunk in the Overworld.(Default: 5)
			#Range: 1 ~ 255
			count_overworld_experience = 5
			#Set the Max Height of the Experience Ore in the Overworld (Default: 128).
			#Range: 0 ~ 256
			max_height_overworld_experience = 128
			#Set the Min Height of the Experience Ore in the Overworld (Default: 0).
			#Range: 0 ~ 128
			min_height_overworld_experience = 0

		["Ore Generation".Experience.End]
			#Enable the Generation of the End Experience Ore (Default: true).
			generate_end_experience = true
			#Set the Count of the Experience Ore how much can spawn per Chunk in  the End (Default: 5).
			#Range: 1 ~ 255
			count_end_experience = 5
			#Set the Min Height of the Experience Ore in  the End (Default: 0).
			#Range: 0 ~ 128
			min_height_end_experience = 0
			#Set the Max Height of the Experience Ore in  the End (Default: 128).
			#Range: 0 ~ 128
			max_height_end_experience = 128

	["Ore Generation".Nether]

		["Ore Generation".Nether."Topaz Generation"]
			#Set the Vein Size of the Topaz Ore (Default: 4).
			#Range: 4 ~ 255
			veinsize_topaz = 4
			#Enable the Generation of Topaz Ore (Default: true).
			generate_topaz = true
			#Set the Max Height of the Topaz Ore (Default: 128).
			#Range: 0 ~ 128
			maxheight_topaz = 128
			#Set the Min Height of the Topaz Ore (Default: 0).
			#Range: 0 ~ 128
			minheight_topaz = 0
			#Set the Count of the Topaz Ore how much can spawn per Chunk (Default: 20).
			#Range: 1 ~ 255
			count_topaz = 20

	["Ore Generation".Overworld]
		#Enable that Rubies and Sapphire's generate in every biome(Default: false).
		every_biome = false

		["Ore Generation".Overworld."Sapphire Generation"]
			#Set the Max Height of the Sapphire Ore (Default: 16).
			#Range: 0 ~ 256
			maxheight_sapphire = 16
			#Set the Count of the Sapphire Ore how much can spawn per Chunk (Default: 1).
			#Range: 1 ~ 255
			count_sapphire = 1
			#Set the Vein Size of the Sapphire Ore (Default: 8).
			#Range: 4 ~ 255
			veinsize_sapphire = 8
			#Set the Min Height of the Sapphire Ore (Default: 0).
			#Range: 0 ~ 256
			minheight_sapphire = 0
			#Enable the Generation of Sapphire Ore (Default: true).
			generate_sapphire = true

		["Ore Generation".Overworld."Ruby Generation"]
			#Enable the Generation of Ruby Ore (Default: true).
			generate_ruby = true
			#Set the Vein Size of the Ruby Ore (Default: 8).
			#Range: 4 ~ 255
			veinsize_ruby = 8
			#Set the Count of the Ruby Ore how much can spawn per Chunk (Default: 1).
			#Range: 1 ~ 255
			count_ruby = 1
			#Set the Min Height of the Ruby Ore (Default: 0).
			#Range: 0 ~ 256
			minheight_ruby = 0
			#Set the Max  Height of the Ruby Ore (Default: 16).
			#Range: 0 ~ 256
			maxheight_ruby = 16

	["Ore Generation".End]

		["Ore Generation".End."Amethyst Generation"]
			#Set the Count of the Amethyst Ore how much can spawn per Chunk (Default: 10).
			#Range: 1 ~ 255
			count_amethyst = 10
			#Set the Max Height of the Amethyst Ore (Default: 128).
			#Range: 0 ~ 128
			maxheight_amethyst = 128
			#Enable the Generation of Amethyst Ore (Default: true).
			generate_amethyst = true
			#Set the Min Height of the Amethyst Ore (Default: 0).
			#Range: 0 ~ 128
			minheight_amethyst = 0

["Tool Durabilities"]

	["Tool Durabilities".Sapphire]
		#Set the Durability of Sapphire Tools(Default: 1700).
		#Range: 0 ~ 999999999
		durability_sapphire = 1700

	["Tool Durabilities".Ruby]
		#Set the Durability of Ruby Tools(Default: 1700).
		#Range: 0 ~ 999999999
		durability_ruby = 1700

	["Tool Durabilities".Topaz]
		#Set the Durability of Topaz Tools(Default: 1800).
		#Range: 0 ~ 999999999
		durability_topaz = 1800

	["Tool Durabilities".Amethyst]
		#Set the Durability of Amethyst Tools(Default: 2000).
		#Range: 0 ~ 999999999
		durability_amethyst = 2000

